package com.jagex.runescape.config;

public final class IncomingPacketIds {

    public static final int
            REMOVE_LANDSCAPE_OBJECT = 88,
            SET_LANDSCAPE_OBJECT = 152,
            REMOVE_GROUND_ITEM = 208,
    UPDATE_GROUND_ITEM_AMOUNT = 121,
    SET_GROUND_ITEM = 107,
    SET_PLAYER_GROUND_ITEM = 106,

    SHOW_STILL_GRAPHICS = 59,
    SHOW_PROJECTILE = 181,

    PLAY_SOUND = 41,

    SET_INTERFACE_SCROLL_POSITION = 200,
    UPDATE_INTERFACE_STRING = 232,
    RESET_INTERFACE_SETTINGS = 113,
    FLASH_SIDEBAR_ICON = 238,
    SET_SIDEBAR_INTERFACE = 10,

    CLEAR_INTERFACE_ITEMS = 219,

    PLAYER_UPDATING = 90,
    NPC_UPDATING = 71,

    UPDATE_FRIEND_LIST_STATUS = 251,
    UPDATE_IGNORE_LIST = 226,

    SEND_REFERENCE_POSITION = 75,

    UPDATE_MEMBERSHIP_AND_WORLD_INDEX = 126,

    RESET_CUTSCENE_CAMERA = 148;

}
